# Generated by Django 6.0.1 on 2026-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
