# Generated by Django 6.0.1 on 2026-04-06 19:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_point_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopage',
            name='content',
            field=wagtail.fields.StreamField([('slider', 3), ('header', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Слайдер', 'max_num': 10, 'min_num': 3}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок'}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline'], 'label': 'Описание', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {'label': 'Заглавный блок'})}),
        ),
    ]
