# Generated by Django 6.0.1 on 2026-04-07 15:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_geopage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geopage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='geopage',
            name='intro',
        ),
        migrations.AlterField(
            model_name='geopage',
            name='content',
            field=wagtail.fields.StreamField([('slider', 4), ('header', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('image', 0), ('caption', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'label': 'Слайды', 'max_num': 10, 'min_num': 3}), 4: ('wagtail.blocks.StructBlock', [[('slides', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline'], 'label': 'Описание', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6)]], {'label': 'Заглавный блок'})}),
        ),
    ]
