# Generated by Django 6.0.1 on 2026-04-07 16:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_remove_geopage_body_remove_geopage_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geopage',
            name='content',
            field=wagtail.fields.StreamField([('header', 2), ('slider', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Заголовок', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline'], 'label': 'Описание', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1)]], {'label': 'Заглавный блок'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Подпись', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'label': 'Слайды', 'max_num': 10, 'min_num': 3}), 7: ('wagtail.blocks.StructBlock', [[('slides', 6)]], {})}),
        ),
    ]
