# Generated by Django 6.0.1 on 2026-05-08 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_alter_geopage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_messages_points', to='points.point'),
        ),
    ]
