# Generated by Django 6.0.1 on 2026-05-17 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_artifact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'verbose_name': 'Артефакт', 'verbose_name_plural': 'Артефакты'},
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='synced_at',
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='fastapi_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
