# Generated by Django 6.0.1 on 2026-05-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_alter_artifact_options_remove_artifact_synced_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='fastapi_id',
        ),
    ]
