# Generated by Django 6.0.1 on 2026-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_remove_artifact_fastapi_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='created_at',
        ),
        migrations.AddField(
            model_name='artifact',
            name='fastapi_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='synced_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
