# Generated by Django 6.0.1 on 2026-05-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_remove_artifact_created_at_artifact_fastapi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
